travis:
  secure:
    BINSTAR_TOKEN: ROW80E+pnnUsqLcVNTZ9ihAiPGr28KEVELbmLarD611agn6HF2FiH4abG5Du059jm8BYOnLnM6z0vD9jABeti9SdUn/xDlhy7BXitdxnVelf/8cJeF9SQsE4tjkbHkVcLToK0dEWiWYEgw117PTZHQgzmZIksMSVD636CRY2BkcFksaBBuUlrEpoGYjJFvF34WsLigCw8SsykFQVOG93IHs0PLyKXSLEp64YSMvIl6PsUASDYMkNU2klzZrPumTXPvnAG8YV+FS4xSgaGv0mQZGJqht8UhNQfWvQT+RwNOb4nMGslZYzHj8UNEJNbF/NbD5hLE/O3GqUjXquL3+vDdHzE/StZvJbI9VUfWx7twMSiHj5kfUyrWnHZBjrXlTNbCiabEeptegjRNgsBABqy8XibngxQivIk4xwHeSwUIey10T05EHjdwuH2NKgKaMx9bnmA5A3RmtudymPojUHuTCyJlhq5cxhJGwGx4KNdNIU5Ex2NbuD9NBpq9cK1FG9sfuRTX7tTZU2vt+LWrYb0uOr5skmkZE7wTbXs3a5ITnFpTQYf9kuKJgloc+ufDBcEvC1+jqVKHTEfy7LfE36/+QJlbnsXfpWILnbwdoaqgy5PhxrfKSOUFhYIi2IwKm20fz5lMkXS7XcffB0Cy2qcwyjmK5E9j73IjbeqWxu060=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
